---
title: "SIGSCE Replication"
author: "Karrie Chou"
date: "19/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(tinytex)
```

## Data setup
```{r}
setwd("~/Desktop/OnTrack")

merged_prototype <- read.csv("merged_prototype.csv")
sigcse_dependent_variables <- read.csv("sigcse_dependent_variables.csv")

merged_prototype_students <- 
  merged_prototype %>%
  filter(ca_consent == "True")
```

## Page 4 Table 1: Control and Treatment Groups A/B Comparisons: Start and End Times

```{r, include=FALSE}
table_1_data <- inner_join(sigcse_dependent_variables, merged_prototype_students, by = c("hashedid"))
table_1_starters_data <- 
  table_1_data %>%
  filter(w7_started == 'True')

# Creating datasets: 
table_1_starters_email <- 
  table_1_starters_data %>%
  filter(w7_contral_treat_label == 'Get email')

table_1_starters_no_email <-
  table_1_starters_data %>%
  filter(w7_contral_treat_label == 'No email')

table_1_email <-
  table_1_data %>%
  mutate(w7_starttime_num = ifelse(is.na(w7_starttime), 0, w7_starttime), 
         w7_endtime_num = ifelse(is.na(w7_endtime), 0, w7_endtime)) %>%
  filter(w7_contral_treat_label == 'Get email')

table_1_no_email <- 
  table_1_data %>%
  mutate(w7_starttime_num = ifelse(is.na(w7_starttime), 0, w7_starttime), 
         w7_endtime_num = ifelse(is.na(w7_endtime), 0, w7_endtime)) %>%
  filter(w7_contral_treat_label == 'No email')

# Start times: 
## Forming individual tables to rbind: 
table_1_email_starttime <- 
  table_1_starters_email %>%
  summarize(mean = round(mean(w7_starttime), 2), sem = round(sqrt(var(w7_starttime)/nrow(table_1_starters_data)), 2), 
            n = nrow(table_1_starters_email))

table_1_no_email_starttime <-
  table_1_starters_no_email %>%
  summarize(mean = round(mean(w7_starttime), 2), sem = round(sqrt(var(w7_starttime)/nrow(table_1_starters_data)), 2), 
              n = nrow(table_1_starters_no_email))

table_1_email_starttime_nonstarters <-
  table_1_email %>%
  summarize(mean = round(mean(w7_starttime_num), 2), sem = round(sqrt(var(w7_starttime_num)/nrow(table_1_data)), 2), 
            n = nrow(table_1_email))

table_1_no_email_starttime_nonstarters <-
  table_1_no_email %>%
  summarize(mean = round(mean(w7_starttime_num), 2), sem = round(sqrt(var(w7_starttime_num)/nrow(table_1_data)), 2), 
            n = nrow(table_1_no_email))

## rbind-ing and c-binding: 
starttime <- rbind(table_1_email_starttime, table_1_no_email_starttime)
starttime_nonstarters <- rbind(table_1_email_starttime_nonstarters, table_1_no_email_starttime_nonstarters)

final_starttime <- cbind(starttime, starttime_nonstarters)

# End times: 
## Forming individual tables to rbind: 
table_1_email_endtime <- 
  table_1_starters_email %>%
  summarize(mean = round(mean(w7_endtime), 2), sem = round(sqrt(var(w7_endtime)/nrow(table_1_starters_data)), 2), 
            n = nrow(table_1_starters_email))

table_1_no_email_endtime <-
  table_1_starters_no_email %>%
  summarize(mean = round(mean(w7_endtime), 2), sem = round(sqrt(var(w7_endtime)/nrow(table_1_starters_data)), 2), 
            n = nrow(table_1_starters_no_email))

table_1_email_endtime_nonstarters <-
  table_1_email %>%
  summarize(mean = round(mean(w7_endtime_num), 2), sem = round(sqrt(var(w7_endtime_num)/nrow(table_1_data)), 2), 
            n = nrow(table_1_email))

table_1_no_email_endtime_nonstarters <-
  table_1_no_email %>%
  summarize(mean = round(mean(w7_endtime_num), 2), sem = round(sqrt(var(w7_endtime_num)/nrow(table_1_data)), 2), 
            n = nrow(table_1_no_email))

## rbind-ing and c-binding: 
endtime <- rbind(table_1_email_endtime, table_1_no_email_endtime)
endtime_nonstarters <- rbind(table_1_email_endtime_nonstarters, table_1_no_email_endtime_nonstarters)

final_endtime <- cbind(endtime, endtime_nonstarters)

# Final table: 
control_vs_treatment <- c('Email', "No email")
table_1 <- cbind(control_vs_treatment, final_starttime, final_endtime)
```

```{r}
kable(table_1)
```

## Page 5 Table 3: Email Versions A/B Comparisons: Start and End Times

```{r, include=FALSE}
table_3_data <- inner_join(sigcse_dependent_variables, merged_prototype_students, by = c("hashedid"))
table_3_starters_data <- 
  table_3_data %>%
  filter(w7_started == 'True')

## Creating datasets: 
table_3_wed_aft_starters_data <-
  table_3_starters_data %>%
  filter(w7_wed_email == 1, w7_afternoon_email == 1)

table_3_wed_eve_starters_data <- 
  table_3_starters_data %>%
  filter(w7_wed_email == 1, w7_afternoon_email == 0)

table_3_thurs_aft_starters_data <-
  table_3_starters_data %>%
  filter(w7_wed_email == 0, w7_afternoon_email == 1)

table_3_wed_aft_data <-
  table_3_data %>%
  mutate(w7_starttime_num = ifelse(is.na(w7_starttime), 0, w7_starttime), 
         w7_endtime_num = ifelse(is.na(w7_endtime), 0, w7_endtime)) %>%
  filter(w7_wed_email == 1, w7_afternoon_email == 1)

table_3_wed_eve_data <- 
  table_3_data %>%
  mutate(w7_starttime_num = ifelse(is.na(w7_starttime), 0, w7_starttime), 
         w7_endtime_num = ifelse(is.na(w7_endtime), 0, w7_endtime)) %>%
  filter(w7_wed_email == 1, w7_afternoon_email == 0)

table_3_thurs_aft_data <-
  table_3_data %>%
  mutate(w7_starttime_num = ifelse(is.na(w7_starttime), 0, w7_starttime), 
         w7_endtime_num = ifelse(is.na(w7_endtime), 0, w7_endtime)) %>%
  filter(w7_wed_email == 0, w7_afternoon_email == 1)

# Start times: 
## Forming individual tables to rbind: 
table_3_wed_aft_starttime <- 
  table_3_wed_aft_starters_data %>%
  summarize(mean = round(mean(w7_starttime), 2), sem = round(sqrt(var(w7_starttime)/nrow(table_3_starters_data)), 2), 
            n = nrow(table_3_wed_aft_starters_data))

table_3_wed_eve_starttime <- 
  table_3_wed_eve_starters_data %>%
  summarize(mean = round(mean(w7_starttime), 2), sem = round(sqrt(var(w7_starttime)/nrow(table_3_starters_data)), 2), 
            n = nrow(table_3_wed_aft_starters_data))

table_3_thurs_aft_starttime <- 
  table_3_thurs_aft_starters_data %>%
  summarize(mean = round(mean(w7_starttime), 2), sem = round(sqrt(var(w7_starttime)/nrow(table_3_starters_data)), 2), 
            n = nrow(table_3_wed_aft_starters_data))

table_3_wed_aft_starttime_nonstarters <- 
  table_3_wed_aft_data %>%
  summarize(mean = round(mean(w7_starttime_num), 2), sem = round(sqrt(var(w7_starttime_num)/nrow(table_3_data)), 2), 
            n = nrow(table_3_wed_aft_data))

table_3_wed_eve_starttime_nonstarters <- 
  table_3_wed_eve_data %>%
  summarize(mean = round(mean(w7_starttime_num), 2), sem = round(sqrt(var(w7_starttime_num)/nrow(table_3_data)), 2), 
            n = nrow(table_3_wed_eve_data))

table_3_thurs_aft_starttime_nonstarters <- 
  table_3_thurs_aft_data %>%
  summarize(mean = round(mean(w7_starttime_num), 2), sem = round(sqrt(var(w7_starttime_num)/nrow(table_3_data)), 2), 
            n = nrow(table_3_thurs_aft_data))

## rbind-ing and cbind-ing: 
wed_aft_starttime <- cbind(table_3_wed_aft_starttime, table_3_wed_aft_starttime_nonstarters)
wed_eve_starttime <- cbind(table_3_wed_eve_starttime, table_3_wed_eve_starttime_nonstarters)
thurs_aft_starttime <- cbind(table_3_thurs_aft_starttime, table_3_thurs_aft_starttime_nonstarters)

final_starttime_3 <- rbind(wed_aft_starttime, wed_eve_starttime, thurs_aft_starttime)

# End times: 
## Forming individual tables to rbind: 
table_3_wed_aft_endtime <- 
  table_3_wed_aft_starters_data %>%
  summarize(mean = round(mean(w7_endtime), 2), sem = round(sqrt(var(w7_endtime)/nrow(table_3_starters_data)), 2), 
            n = nrow(table_3_wed_aft_starters_data))

table_3_wed_eve_endtime <- 
  table_3_wed_eve_starters_data %>%
  summarize(mean = round(mean(w7_endtime), 2), sem = round(sqrt(var(w7_endtime)/nrow(table_3_starters_data)), 2), 
            n = nrow(table_3_wed_eve_starters_data))

table_3_thurs_aft_endtime <- 
  table_3_thurs_aft_starters_data %>%
  summarize(mean = round(mean(w7_endtime), 2), sem = round(sqrt(var(w7_endtime)/nrow(table_3_starters_data)), 2), 
            n = nrow(table_3_thurs_aft_starters_data))

table_3_wed_aft_endtime_nonstarters <- 
  table_3_wed_aft_data %>%
  summarize(mean = round(mean(w7_endtime_num), 2), sem = round(sqrt(var(w7_endtime_num)/nrow(table_3_data)), 2), 
            n = nrow(table_3_wed_aft_data))

table_3_wed_eve_endtime_nonstarters <- 
  table_3_wed_eve_data %>%
  summarize(mean = round(mean(w7_endtime_num), 2), sem = round(sqrt(var(w7_endtime_num)/nrow(table_3_data)), 2), 
            n = nrow(table_3_wed_eve_data))

table_3_thurs_aft_endtime_nonstarters <- 
  table_3_thurs_aft_data %>%
  summarize(mean = round(mean(w7_endtime_num), 2), sem = round(sqrt(var(w7_endtime_num)/nrow(table_3_data)), 2), 
            n = nrow(table_3_thurs_aft_data))

## rbind-ing and cbind-ing: 
wed_aft_endtime <- cbind(table_3_wed_aft_endtime, table_3_wed_aft_endtime_nonstarters)
wed_eve_endtime <- cbind(table_3_wed_eve_endtime, table_3_wed_eve_endtime_nonstarters)
thurs_aft_endtime <- cbind(table_3_thurs_aft_endtime, table_3_thurs_aft_endtime_nonstarters)

final_endtime_3 <- rbind(wed_aft_endtime, wed_eve_endtime, thurs_aft_endtime)

# Final table: 
email_group <- c('Wednesday afternoon', "Wednesday evening", "Thursday afternoon")
table_3 <- cbind(email_group, final_starttime_3, final_endtime_3)
```

```{r}
kable(table_3)
```
## Page 5 Table 4: Email Versions A/B Comparisons: Attempt, Completion and Link Click Rates

```{r, include=FALSE}
table_4_data <- inner_join(sigcse_dependent_variables, merged_prototype_students, by = c("hashedid"))

# Creating datasets: 
table_4_wed_aft_data <-
  table_4_data %>%
  filter(w7_wed_email == 1, w7_afternoon_email == 1)

table_4_wed_eve_data <- 
  table_4_data %>%
  filter(w7_wed_email == 1, w7_afternoon_email == 0)

table_4_thurs_aft_data <-
  table_4_data %>%
  filter(w7_wed_email == 0, w7_afternoon_email == 1)

wed_aft_attempted_count = 0
for (i in 1:nrow(table_4_wed_aft_data)){
  if (table_4_wed_aft_data$w7_started[i] == 'True'){
    wed_aft_attempted_count = wed_aft_attempted_count + 1
  }
}
wed_aft_proportion_attempted = wed_aft_attempted_count/nrow(table_4_wed_aft_data)

wed_aft_completed_count = 0
for (i in 1:nrow(table_4_wed_aft_data)){
  if (table_4_wed_aft_data$w7_complete[i] == 'True'){
    wed_aft_completed_count = wed_aft_completed_count + 1
  }
}
wed_aft_proportion_completed = wed_aft_completed_count/nrow(table_4_wed_aft_data)

wed_aft_data <- 
  table_4_data %>%
  summarize(proportion_attempted = round(wed_aft_proportion_attempted, 2), 
            proportion_completed = round(wed_aft_proportion_completed, 2), 
            n = nrow(table_4_wed_aft_data))

wed_eve_attempted_count = 0
for (i in 1:nrow(table_4_wed_eve_data)){
  if (table_4_wed_eve_data$w7_started[i] == 'True'){
    wed_eve_attempted_count = wed_eve_attempted_count + 1
  }
}
wed_eve_proportion_attempted = wed_eve_attempted_count/nrow(table_4_wed_eve_data)

wed_eve_completed_count = 0
for (i in 1:nrow(table_4_wed_eve_data)){
  if (table_4_wed_eve_data$w7_complete[i] == 'True'){
    wed_eve_completed_count = wed_eve_completed_count + 1
  }
}
wed_eve_proportion_completed = wed_eve_completed_count/nrow(table_4_wed_eve_data)

wed_eve_data <- 
  table_4_data %>%
  summarize(proportion_attempted = round(wed_eve_proportion_attempted, 2), 
            proportion_completed = round(wed_eve_proportion_completed, 2), 
            n = nrow(table_4_wed_eve_data))

thurs_aft_attempted_count = 0
for (i in 1:nrow(table_4_thurs_aft_data)){
  if (table_4_thurs_aft_data$w7_started[i] == 'True'){
    thurs_aft_attempted_count = thurs_aft_attempted_count + 1
  }
}
thurs_aft_proportion_attempted = thurs_aft_attempted_count/nrow(table_4_thurs_aft_data)

thurs_aft_completed_count = 0
for (i in 1:nrow(table_4_thurs_aft_data)){
  if (table_4_thurs_aft_data$w7_complete[i] == 'True'){
    thurs_aft_completed_count = thurs_aft_completed_count + 1
  }
}
thurs_aft_proportion_completed = thurs_aft_completed_count/nrow(table_4_thurs_aft_data)

thurs_aft_data <- 
  table_4_data %>%
  summarize(proportion_attempted = round(thurs_aft_proportion_attempted, 2), 
            proportion_completed = round(thurs_aft_proportion_completed, 2), 
            n = nrow(table_4_thurs_aft_data))

# rbind-ing and cbind-ing: 
table_4_data <- rbind(wed_aft_data, wed_eve_data, thurs_aft_data)
table_4 <- cbind(email_group, table_4_data)
```

```{r}
kable(table_4)
```
## Page 5 Graph

```{r, include=FALSE}
graph_data <- inner_join(sigcse_dependent_variables, merged_prototype_students, by = c("hashedid"))

control_count = 0
for (i in 1:nrow(graph_data)){
  if (graph_data$w7_contral_treat_label[i] == 'No email'){
    control_count = control_count + 1
  }
}

treatment_count = 0
for (i in 1:nrow(graph_data)){
  if (graph_data$w7_contral_treat_label[i] == 'Get email'){
    treatment_count = treatment_count + 1
  }
}

attempted <- 
  graph_data %>%
  filter(w7_started == 'True')

control_attempted = 0
for (i in 1:nrow(attempted)){
  if (attempted$w7_contral_treat_label[i] == 'No email'){
    control_attempted = control_attempted + 1
  }
}

treatment_attempted = 0
for (i in 1:nrow(attempted)){
  if (attempted$w7_contral_treat_label[i] == 'Get email'){
    treatment_attempted = treatment_attempted + 1
  }
}

plot_info <- data.frame(x_axis = c('Treatment', 'Control'), 
                        y_axis = c(treatment_attempted/treatment_count, control_attempted/control_count))
attempt_graph <- ggplot(data = plot_info, aes(x = x_axis, y = y_axis)) + geom_bar(stat="identity", fill = 'steelblue') + 
  labs(x = 'Condition', y = 'Probability of attempting')
```